import json
import logging
from typing import Any

from langchain_openai import ChatOpenAI
from utils.knowledge_base import KnowledgeBase
import config

logger = logging.getLogger(__name__)


def _mock_resolution_response(triage: dict[str, Any]) -> dict[str, Any]:
    logger.info("ResolutionAgent running in MOCK_MODE — skipping LLM and KB calls")
    category = triage.get("category", "general")
    priority = triage.get("priority", "P2")
    return {
        "ticket_title": f"{priority} {category.title()}: Issue detected on production",
        "ticket_description": (
            f"An issue of category '{category}' has been detected with priority {priority}. "
            f"Historical context: {triage.get('log_summary', 'No log data available.')} "
            "This ticket was auto-generated by the JIRA Workflow Agent."
        ),
        "resolution_steps": [
            "1. Acknowledge the alert in PagerDuty",
            "2. Check service health dashboard",
            "3. Follow the relevant runbook for this category",
            "4. Update this ticket with findings every 30 minutes",
            "5. Mark resolved once service health confirmed",
        ],
        "affected_systems": ["production-cluster", "api-gateway", "monitoring"],
        "escalation_path": triage.get("recommended_action", "assign_to_on_call"),
        "estimated_resolution_time": "2 hours",
        "runbooks_referenced": ["mock-runbook-001"],
    }


class ResolutionAgent:
    """Generates a structured JIRA ticket draft using RAG over internal runbooks."""

    def __init__(self):
        logger.info(
            "Initialising ResolutionAgent | model=%s | mock=%s",
            config.LLM_MODEL, config.MOCK_MODE
        )
        self.mock_mode = config.MOCK_MODE
        self.knowledge_base = KnowledgeBase()

        # Skip embedding API calls during local testing — KB is only needed in production
        if not self.mock_mode:
            self.knowledge_base.build()

        # temperature=0.2 allows natural language variation in ticket descriptions
        # while keeping structured fields (priority, steps) deterministic
        self.llm = ChatOpenAI(
            model=config.LLM_MODEL,
            max_tokens=config.LLM_MAX_TOKENS,
            temperature=0.2,
            api_key=config.OPENAI_API_KEY,
        )

    def _build_prompt(self, triage: dict, retrieved_docs: list) -> str:
        runbook_context = "\n\n---\n\n".join([
            f"Source: {doc.metadata.get('source', 'unknown')}\n{doc.page_content}"
            for doc in retrieved_docs
        ])

        return f"""
        You are a senior engineer drafting a JIRA incident ticket and resolution plan.

        TRIAGE CONTEXT:
        Category: {triage.get('category')}
        Priority: {triage.get('priority')}
        Log Summary: {triage.get('log_summary')}
        Recommended Action: {triage.get('recommended_action')}

        RELEVANT INTERNAL RUNBOOKS:
        {runbook_context}

        Using the triage context and runbooks above, generate a JIRA ticket.
        Return ONLY a valid JSON object with these exact keys:

        {{
            "ticket_title": "concise title starting with priority and category",
            "ticket_description": "2-3 sentence description of the issue and impact",
            "resolution_steps": ["step 1", "step 2", "step 3"],
            "affected_systems": ["system1", "system2"],
            "escalation_path": "team or channel to escalate to",
            "estimated_resolution_time": "X hours",
            "runbooks_referenced": ["runbook-id-1"]
        }}

        Base your resolution steps on the runbooks provided.
        Do not invent systems or commands not present in the runbooks.
        Return ONLY the JSON. No explanation, no markdown, no code fences.
        """

    def run(self, triage: dict[str, Any]) -> dict[str, Any]:
        """
        Retrieves relevant runbooks and generates a structured ticket draft.

        Raises:
            ValueError: If the LLM returns malformed JSON.
        """
        logger.info(
            "ResolutionAgent.run() | category=%s | priority=%s",
            triage.get("category"), triage.get("priority")
        )

        if self.mock_mode:
            return _mock_resolution_response(triage)

        search_query = (
            f"{triage.get('category', '')} "
            f"{triage.get('log_summary', '')} "
            f"{triage.get('recommended_action', '')}"
        )

        retrieved_docs = self.knowledge_base.search(query=search_query, top_k=2)
        logger.info(
            "Runbooks retrieved | count=%d | sources=%s",
            len(retrieved_docs),
            [d.metadata.get("source") for d in retrieved_docs]
        )

        prompt = self._build_prompt(triage=triage, retrieved_docs=retrieved_docs)

        logger.info("Calling LLM | model=%s", config.LLM_MODEL)
        response = self.llm.invoke(prompt)
        raw_content = response.content.strip()

        try:
            result = json.loads(raw_content)
        except json.JSONDecodeError as e:
            logger.error("Resolution LLM returned invalid JSON | error=%s | raw='%s'", str(e), raw_content[:300])
            raise ValueError(f"ResolutionAgent received non-JSON response: {raw_content[:200]}") from e

        logger.info(
            "Resolution complete | title='%s' | steps=%d",
            result.get("ticket_title", "")[:60],
            len(result.get("resolution_steps", []))
        )
        return result


# Singleton — reused across Lambda warm starts to avoid re-initialising the LLM client and KB
resolution_agent = ResolutionAgent()


def run_resolution(state: dict) -> dict:
    """LangGraph node — reads 'triage' from state, writes 'resolution' back."""
    logger.info("Node: resolution | state_keys=%s", list(state.keys()))
    triage = state.get("triage", {})
    if not triage:
        logger.warning("Resolution node received empty triage state")
    return {"resolution": resolution_agent.run(triage)}